language: go

go:
  - 1.12.x

env:
  - GO111MODULES=on

install:
  - mkdir /tmp/sdk
  - curl -o /tmp/sdk.tar.gz "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-255.0.0-linux-x86_64.tar.gz"
  - tar xzf /tmp/sdk.tar.gz -C /tmp/sdk
  - export PATH="$PATH:/tmp/sdk/bin"
  - export APPENGINE_DEV_APPSERVER=/tmp/sdk/bin/dev_appserver.py

script:
  - make test
