btCompletePayment = "Complete payment to Register"
btContinueToCheckout = "Continue to checkout"
btSendVerifEmail = "Send verification email"
erProcessPayment = "Could not process payment"
fmAmount = "Amount {{ .CostPrint }} {{ .Currency }}"
fmCity = "City"
fmCountry = "Country"
fmEnterEmail = "Please enter your email address"
fmFirstName = "First name"
fmILiveIn = "I live in..."
fmPaymentDetails = "Payment Details"
fmSameEmail = "Email - use the same one you verified with"
fmYourDetails = "Your Details"
pgCheckEmail = "Please check your email inbox, and click the link we've sent you"
pgNowRegistered = "You are now registered!"
pgRegisterFor = "Register for {{ .Name }}"
pgRegisteredFor = "Registered for {{ .Name }}"
vlEnterEmail = "Please enter a valid email address so we can send you convention details."
vlFirstName = "Valid first name is required."
vlSameEmail = "Please enter a valid email address so we can send you convention details."
